import Link from 'next/link';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gray-950">
      <header className="border-b border-gray-800 px-6 py-4 flex items-center gap-4">
        <Link href="/" className="text-gray-500 hover:text-gray-300 text-sm">← Back</Link>
        <h1 className="text-xl font-black tracking-widest text-white">CLASR</h1>
      </header>
      <main className="max-w-2xl mx-auto px-6 py-12">
        <h2 className="text-2xl font-bold text-white mb-2">Terms of Service</h2>
        <p className="text-gray-500 text-xs mb-8">Last updated: April 2025</p>

        <div className="space-y-6 text-gray-400 text-sm leading-relaxed">
          <section>
            <h3 className="text-white font-semibold mb-2">1. Service Description</h3>
            <p>CLASR is an AI-powered academic manuscript signal reading tool. It identifies structural, methodological, citation-related, and evidence-boundary signals in English academic manuscripts. CLASR does not make publication decisions, does not act as a peer reviewer or journal editor, and does not guarantee acceptance or rejection outcomes.</p>
          </section>

          <section>
            <h3 className="text-white font-semibold mb-2">2. Acceptable Use</h3>
            <p>You may use CLASR only for lawful purposes. You agree not to submit content that violates third-party intellectual property rights, contains personal data of others without consent, or is designed to circumvent the service's intended function. You are responsible for the content you submit.</p>
          </section>

          <section>
            <h3 className="text-white font-semibold mb-2">3. Manuscript Content</h3>
            <p>By submitting a manuscript, you confirm that you have the right to share it for analysis purposes. CLASR does not claim ownership of submitted content. Manuscript text is processed to generate your report and is not stored permanently or shared with third parties.</p>
          </section>

          <section>
            <h3 className="text-white font-semibold mb-2">4. Subscription and Billing</h3>
            <p>Paid plans are billed in advance on a monthly or annual basis via Stripe. You may cancel your subscription at any time through your account settings. Cancellation takes effect at the end of the current billing period. Refunds are not provided for partial periods unless required by applicable law.</p>
          </section>

          <section>
            <h3 className="text-white font-semibold mb-2">5. Free Plan Limits</h3>
            <p>The Free plan provides 3 lifetime analyses. These analyses do not reset. Upgrading to a paid plan provides a monthly analysis allowance as described on the pricing page.</p>
          </section>

          <section>
            <h3 className="text-white font-semibold mb-2">6. No Academic Guarantee</h3>
            <p>CLASR's reports are signal-based outputs generated by AI. They are intended as a preparatory aid, not as a substitute for expert peer review. CLASR makes no warranty regarding the accuracy, completeness, or fitness for any particular academic purpose of its outputs.</p>
          </section>

          <section>
            <h3 className="text-white font-semibold mb-2">7. Limitation of Liability</h3>
            <p>To the maximum extent permitted by law, CLASR and its operators are not liable for any indirect, incidental, or consequential damages arising from use of the service, including publication outcomes, editorial decisions, or academic consequences.</p>
          </section>

          <section>
            <h3 className="text-white font-semibold mb-2">8. Account Termination</h3>
            <p>We reserve the right to suspend or terminate accounts that violate these terms. You may delete your account at any time by contacting support.</p>
          </section>

          <section>
            <h3 className="text-white font-semibold mb-2">9. Changes to Terms</h3>
            <p>We may update these terms from time to time. Continued use of CLASR after changes constitutes acceptance of the updated terms.</p>
          </section>

          <section>
            <h3 className="text-white font-semibold mb-2">10. Contact</h3>
            <p>Questions about these terms: <span className="text-blue-400">support@clasr.com</span></p>
          </section>
        </div>
      </main>
    </div>
  );
}
